steps:
  # Build and push frontend
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'kitsup-front'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/kitsup-front', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kitsup-front']

  # Deploy frontend with proper resources
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'kitsup-front'
      - '--image=gcr.io/$PROJECT_ID/kitsup-front'
      - '--platform=managed'
      - '--region=asia-south1'
      - '--allow-unauthenticated'
      - '--port=80'
      - '--memory=512Mi'
      - '--cpu=1'

  # Build and push backend
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'kitsup-backend'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/kitsup-backend', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kitsup-backend']

  # Deploy backend with secrets
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'kitsup-backend'
      - '--image=gcr.io/$PROJECT_ID/kitsup-backend'
      - '--platform=managed'
      - '--region=asia-south1'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances=$PROJECT_ID:asia-south1:kitsquiz'
      - '--set-env-vars=INSTANCE_CONNECTION_NAME=$PROJECT_ID:asia-south1:kitsquiz'
      - '--set-env-vars=NODE_ENV=production'
      - '--update-secrets=DB_PASSWORD=DB_PASSWORD:latest'
      - '--update-secrets=SECRET_KEY=SECRET_KEY:latest'
      - '--port=8080'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=1'
      - '--max-instances=3'

images:
  - 'gcr.io/$PROJECT_ID/kitsup-front'
  - 'gcr.io/$PROJECT_ID/kitsup-backend'

options:
  logging: CLOUD_LOGGING_ONLY