steps:
  # Build frontend
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'kitsup-front'    # This folder must contain your React Vite app & Dockerfile
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/kitsup-front', '.']


  # Deploy frontend
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'kitsup-front'
      - '--image=gcr.io/$PROJECT_ID/kitsup-front'
      - '--platform=managed'
      - '--region=asia-south1'
      - '--allow-unauthenticated'

  # Build backend
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'kitsup-backend'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/kitsup-backend', '.']

  # Deploy backend WITHOUT secret manager
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'kitsup-backend'
      - '--image=gcr.io/$PROJECT_ID/kitsup-backend'
      - '--platform=managed'
      - '--region=asia-south1'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DB_HOST=${_DB_HOST},DB_USER=${_DB_USER},DB_PASS=${_DB_PASSWORD},DB_NAME=${_DB_NAME}'

images:
  - 'gcr.io/$PROJECT_ID/kitsup-front'
  - 'gcr.io/$PROJECT_ID/kitsup-backend'

substitutions:
  _DB_HOST: 34.93.43.63
  _DB_USER: root
  _DB_PASSWORD: root # <-- directly put your DB password here
  _DB_NAME: kitsquizdatabase
